print("Enter the value of a,b,c in ax2+bx+c\n")
a=int(input("a="))
b=int(input("b="))
c=int(input("c="))
d=((b**2)-4*a*c)**(1/2)
root1=(-b+d)/(2*a)
root2=(-b-d)/(2*a)
print("root1=",root1)
print("root2=",root2)
